SELECT distinct [TAB]
      ,[IdOrdenAtencion]
      ,[LineaOrdenAtencion]
      ,[IdConsultaExterna]
      ,[Componente]
      ,[Cantidad]
      ,[Forma]
      ,[Dosis]
      ,[DiasTratamiento]
      ,[Frecuencia]
      ,[Comentario]
      ,[IndicadorEPS]
      ,[TipoReceta]
      ,[Estado]
      ,[UsuarioCreacion]
      ,[FechaCreacion]
      ,[UsuarioModificacion]
      ,[FechaModificacion]
      ,[IdPaciente]
      ,[LIN]
      ,[FAM]
      ,[DCI]
      ,[MED]
      ,[documento]
      ,[tipodocumento]
  FROM [SPRING].[dbo].[VW_SS_HCE_VisorReceta] WHERE DCI LIKE 'MEDICAMENTOS ONCOLOGICOS';