

ALTER TABLE cita DROP CONSTRAINT CK__cita__estado__3B75D760;
ALTER TABLE cita ADD CONSTRAINT CK__cita__estado__3B75D760 
    CHECK ([estado] IN ('CANCELADO', 'EN_CONFLICTO', 'ATENDIDO', 'EN_PROCESO', 'PENDIENTE', 'NO_ASIGNADO', 'REPROGRAMADO'));